In [71]:
import pandas as pd
import numpy as np
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.feature_selection import SelectFromModel
from sklearn import cross_validation
from sklearn.linear_model import LogisticRegression
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import RidgeCV
from sklearn import cross_validation
from sklearn.cross_validation import KFold
from sklearn.cross_validation import cross_val_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

from sklearn.grid_search import GridSearchCV

In [59]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

data = pd.concat([train, test])

In [60]:
data = data.drop('Unnamed: 0', 1)
print data.shape 
data.head(2)

(9996, 1812)


rating    bitter     meaty  piquant     salty      sour     sweet  \
0       4       NaN       NaN      NaN       NaN       NaN       NaN   
1       4  0.833333  0.833333      0.0  0.833333  0.166667  0.166667   

   ingredientcount  numberofservings  totaltimeinseconds     ...      yolks  \
0                5               1.0               900.0     ...        0.0   
1                5              12.0               300.0     ...        0.0   

    yoplait  york  yukon   za  zest  zesty  ziti  zucchini  course_num  
0  0.354794   0.0    0.0  0.0   0.0    0.0   0.0       0.0           2  
1  0.000000   0.0    0.0  0.0   0.0    0.0   0.0       0.0           3  

[2 rows x 1812 columns]

In [61]:
data.describe()

rating       bitter        meaty      piquant        salty  \
count  9996.000000  6763.000000  6763.000000  6763.000000  6763.000000   
mean      3.913766     0.425452     0.379467     0.133989     0.450959   
std       0.489578     0.282824     0.275017     0.255023     0.286736   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       4.000000     0.166667     0.166667     0.000000     0.166667   
50%       4.000000     0.333333     0.166667     0.000000     0.333333   
75%       4.000000     0.666667     0.666667     0.166667     0.833333   
max       5.000000     1.000000     1.000000     0.833333     1.000000   

              sour        sweet  ingredientcount  numberofservings  \
count  6763.000000  6763.000000      9996.000000       9994.000000   
mean      0.426142     0.368525         8.527311          6.899940   
std       0.290511     0.246625         3.674521         21.517772   
min       0.000000     0.000000         1.000000          1.000000   
25%       0.166667     0.166667         6.000000          4.000000   
50%       0.333333     0.166667         8.000000          4.000000   
75%       0.666667     0.500000        10.000000          6.000000   
max       1.000000     1.000000        51.000000        750.000000   

       totaltimeinseconds     ...             yolks      yoplait         york  \
count         9996.000000     ...       9996.000000  9996.000000  9996.000000   
mean          2890.522209     ...          0.004273     0.000709     0.000223   
std           7613.724316     ...          0.037981     0.017120     0.009155   
min             60.000000     ...          0.000000     0.000000     0.000000   
25%           1200.000000     ...          0.000000     0.000000     0.000000   
50%           1800.000000     ...          0.000000     0.000000     0.000000   
75%           3000.000000     ...          0.000000     0.000000     0.000000   
max         504000.000000     ...          0.647370     0.578249     0.441548   

             yukon           za         zest        zesty         ziti  \
count  9996.000000  9996.000000  9996.000000  9996.000000  9996.000000   
mean      0.001481     0.000157     0.006294     0.000229     0.000046   
std       0.022700     0.007905     0.043130     0.009373     0.004620   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       0.000000     0.000000     0.000000     0.000000     0.000000   
max       0.506644     0.439423     0.526785     0.443969     0.461875   

          zucchini   course_num  
count  9996.000000  9996.000000  
mean      0.005431     1.999700  
std       0.042310     1.414249  
min       0.000000     0.000000  
25%       0.000000     1.000000  
50%       0.000000     2.000000  
75%       0.000000     3.000000  
max       0.570819     4.000000  

[8 rows x 1812 columns]

In [62]:
data = data.fillna(value=0)

# Feature Selections

In [63]:
#Extra Tree Classifier
array = data.values
x = array[:,0:1811]
y = array[:,1811]
# #feature extraction
# model = ExtraTreesClassifier()
# mdl = model.fit(x,y)
# importances = mdl.feature_importances_
# print(importances)

# model = SelectFromModel(mdl, prefit=True)
# X_new = model.transform(x)
# print X_new.shape

In [64]:
#train test split
X_train, X_test, Y_train, Y_test = cross_validation.train_test_split(x, y, random_state=10)
print X_train.shape
print X_test.shape

(7497, 1811)
(2499, 1811)


In [65]:
# select models to test on dataset
models=[]
models.append(('LOG', LogisticRegression()))
models.append(('LDA', LinearDiscriminantAnalysis()))
models.append(('CART', DecisionTreeClassifier()))
models.append(('KNN', KNeighborsClassifier()))
models.append(('SVM', SVC()))
models.append(('NB', GaussianNB()))

In [66]:
#cross validation
results=[]
names=[]
for name, model in models:
    kfold = KFold(n = 7497, n_folds = 10, random_state = 10)
    _results = cross_validation.cross_val_score(model, X_train, Y_train, cv = kfold, scoring = 'accuracy')
    results.append(_results)
    names.append(name)
    scores="%s: %f (%f)" % (name, _results.mean(), _results.std())
    print scores

LOG: 0.853269 (0.018951)
LDA: 0.847272 (0.010730)
CART: 0.770443 (0.017189)
KNN: 0.454181 (0.012633)
SVM: 0.353609 (0.007109)
NB: 0.518728 (0.059067)


In [72]:
#create a pipeline 
pipelines=[]
pipelines.append(('ScaledLOG', Pipeline([('Scaler', StandardScaler()),('LOG', LogisticRegression())])))
pipelines.append(('ScaledLDA', Pipeline([('Scaler', StandardScaler()),('LDA', LinearDiscriminantAnalysis())])))
pipelines.append(('ScaledCART', Pipeline([('Scaler', StandardScaler()),('CART', DecisionTreeClassifier())])))
pipelines.append(('ScaledKNN', Pipeline([('Scaler', StandardScaler()),('KNN', KNeighborsClassifier())])))
pipelines.append(('ScaledSVM', Pipeline([('Scaler', StandardScaler()),('SVM', SVC())])))
pipelines.append(('ScaledGNB', Pipeline([('Scaler', StandardScaler()),('GNB', GaussianNB())])))

In [73]:
results=[]
names=[]

for name, model in pipelines:
    kfold=KFold(n=7497,n_folds=10, random_state=10)
    _results=cross_validation.cross_val_score(model,X_train,Y_train,cv=kfold,scoring='accuracy')
    results.append(_results)
    names.append(name)
    scores="%s: %f (%f)" % (name, _results.mean(), _results.std())
    print scores

ScaledLOG: 0.834466 (0.012616)
ScaledLDA: 0.847272 (0.010730)
ScaledCART: 0.768708 (0.017606)
ScaledKNN: 0.690275 (0.013966)
ScaledSVM: 0.823528 (0.012014)
ScaledGNB: 0.584233 (0.022016)


In [20]:
# try ensemble methods
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
ensembles = []
ensembles.append(('AB', AdaBoostClassifier()))
ensembles.append(('GBM', GradientBoostingClassifier()))

In [21]:
results=[]
names=[]
for name, model in ensembles:
    kfold=KFold(n=7508,n_folds=10, random_state=10)
    _results=cross_validation.cross_val_score(model,X_train,Y_train,cv=kfold,scoring='accuracy')
    results.append(_results)
    names.append(name)
    scores="%s: %f (%f)" % (name, _results.mean(), _results.std())
    print scores

AB: 0.720033 (0.018775)
GBM: 0.864677 (0.008707)


In [ ]:
# gridsearch for GBM

gsearch1 = GridSearchCV(estimator = GradientBoostingClassifier(learning_rate=0.1, 
                                                               min_samples_split=500,
                                                               min_samples_leaf=50,
                                                               max_depth=8,max_features='sqrt',
                                                               subsample=0.8,
                                                               random_state=10), 
                        param_grid = param_test1, scoring='roc_auc', n_jobs=4, iid=False, cv=10)

gsearch1.fit(X_train,Y_train)

gsearch1.grid_scores_, gsearch1.best_params_, gsearch1.best_score_

In [78]:
#Tune Logistic regression

from sklearn.grid_search import GridSearchCV
alphas = np.array([0.1, 1.0,10.0,100.0,1000.0])
param_grid = dict(C=alphas)
model = LogisticRegression()
grid = GridSearchCV(estimator=model, param_grid=param_grid)
grid.fit(X_train, Y_train)
print(grid.best_score_)
print(grid.best_estimator_)
print(grid.best_params_)

0.860477524343
LogisticRegression(C=1000.0, class_weight=None, dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=100,
          multi_class='ovr', n_jobs=1, penalty='l2', random_state=None,
          solver='liblinear', tol=0.0001, verbose=0, warm_start=False)
{'C': 1000.0}


In [79]:
# Logistic regression
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

logreg = grid.best_estimator_
logreg.fit(X_train, Y_train)
Y_pred = logreg.predict(X_test)
print len(Y_pred)

print accuracy_score(Y_test, Y_pred )
print confusion_matrix(Y_test,Y_pred )
print classification_report(Y_test, Y_pred)

2499
0.858343337335
[[417  12  11  47  19]
 [ 28 421  29  12  10]
 [  6  55 448   3   0]
 [ 66   3   6 405  17]
 [  9   5   4  12 454]]
             precision    recall  f1-score   support

        0.0       0.79      0.82      0.81       506
        1.0       0.85      0.84      0.85       500
        2.0       0.90      0.88      0.89       512
        3.0       0.85      0.81      0.83       497
        4.0       0.91      0.94      0.92       484

avg / total       0.86      0.86      0.86      2499



In [77]:
from sklearn.ensemble import BaggingClassifier
# Apply ensemble method- Bagging 

def build_bagging_model(x,y):
    bagging = BaggingClassifier(LogisticRegression(),
                                n_estimators = 100, 
                                random_state = 10,
                                max_samples = 1.0,
                                max_features = 0.7,
                                bootstrap = True,
                                bootstrap_features = True)
    bagging.fit(x,y)
    return bagging

# Build a bag of Logreg models
bagging = build_bagging_model(X_train, Y_train)
predicted_y = bagging.predict(X_test)

print "\n Bagging Model Accuracy on training data\n"
print classification_report(Y_test, predicted_y)


 Bagging Model Accuracy on training data

             precision    recall  f1-score   support

        0.0       0.81      0.80      0.80       506
        1.0       0.86      0.83      0.85       500
        2.0       0.90      0.90      0.90       512
        3.0       0.84      0.85      0.84       497
        4.0       0.90      0.93      0.91       484

avg / total       0.86      0.86      0.86      2499

